GET http://localhost:5226/games

###
GET http://localhost:5226/games/4

###  
POST http://localhost:5226/games 
Content-Type: application/json

{
    "title": "GTA 8",
    "genre": "Action-Adventure",
    "price": 99.99,
    "releaseDate": "2026-06-28"
}

###
PUT http://localhost:5226/games/7
Content-Type: application/json

{
    "title": "GTA 10",
    "genre": "Action-Adventure",
    "price": 99.99,
    "releaseDate": "2026-06-28"
}   

###
DELETE http://localhost:5226/games/3

###
GET http://localhost:5226/genres

###
GET http://localhost:5226/genres/1
